version: '3'

services:

  generator:
    build: .
    container_name: generator
    environment:
      KAFKA_BROKER_URL: kafka:29092
      TRANSACTIONS_TOPIC: queueing.raw-frames
      TRANSACTIONS_PER_SECOND: 1000

    volumes:
     - ..:/usr/app/sandbox  #this is for testing the code before commit
    
    working_dir: /usr/app/sandbox/generator
    entrypoint: ["python3", "movie_streamer.py"]
  

networks:
  default:
    external:
      name: kafka-network
